name: Test Workflow

on:
  push:
    branches:
      - "main"

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: |
          npm ci
          npm run build

      - name: Test the application
        run: |
          npm test
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ampersander/joke_app
          
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .

deploy:
    runs-on: ubuntu-latest

    needs: build-test
    
    steps:
      - uses: actions/checkout@v3

      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "joke-app-esgi" #Must be unique in Heroku
          heroku_email: "romain-b49460@hotmail.com"